/*
        scale, size, significance.
*/

-- 1. Total customers by country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;
GO

-- 2. Total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
GO

-- 3. Total customers by marital status
SELECT
    marital_status,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY marital_status
ORDER BY total_customers DESC;
GO

-- 4. Total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;
GO

-- 5. Total products by subcategory
SELECT
    subcategory,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY subcategory
ORDER BY total_products DESC;
GO

-- 6. Average product cost by category
SELECT
    category,
    AVG(cost) AS avg_product_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_product_cost DESC;
GO

-- 7. Total revenue generated by each product category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
GO

-- 8. Total revenue generated by each subcategory
SELECT
    p.subcategory,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC;
GO

-- 9. Total revenue generated by each customer
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- 10. Total quantity of items sold by country
SELECT
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;
GO

-- 11. Total quantity of items sold by product category
SELECT
    p.category,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_items_sold DESC;
GO
    
/* 3 degree cumulative queries*/

-- 12. Average revenue per customer by country
SELECT
    c.country,
    AVG(customer_revenue) AS avg_revenue_per_customer
FROM
(
    SELECT
        f.customer_key,
        SUM(f.sales_amount) AS customer_revenue
    FROM gold.fact_sales f
    GROUP BY f.customer_key
) AS customer_totals
JOIN gold.dim_customers c
    ON c.customer_key = customer_totals.customer_key
GROUP BY c.country
ORDER BY avg_revenue_per_customer DESC;
GO

--13. Average revenue per customer by product category
SELECT
    p.category,
    AVG(customer_revenue) AS avg_revenue_per_customer
FROM
(
    SELECT
        customer_key,
        product_key,
        SUM(sales_amount) AS customer_revenue
    FROM gold.fact_sales
    GROUP BY customer_key, product_key
) t
JOIN gold.dim_products p
    ON p.product_key = t.product_key
GROUP BY p.category
ORDER BY avg_revenue_per_customer DESC;

-- 14. Average quantity purchased per customer by country
SELECT
    c.country,
    AVG(customer_quantity) AS avg_items_per_customer
FROM
(
    SELECT
        customer_key,
        SUM(quantity) AS customer_quantity
    FROM gold.fact_sales
    GROUP BY customer_key
) t
JOIN gold.dim_customers c
    ON c.customer_key = t.customer_key
GROUP BY c.country
ORDER BY avg_items_per_customer DESC;

-- 15. Average revenue per order by category
SELECT
    p.category,
    AVG(order_revenue) AS avg_order_value
FROM
(
    SELECT
        order_number,
        product_key,
        SUM(sales_amount) AS order_revenue
    FROM gold.fact_sales
    GROUP BY order_number, product_key
) t
JOIN gold.dim_products p
    ON p.product_key = t.product_key
GROUP BY p.category
ORDER BY avg_order_value DESC;

-- 16. Average revenue per product within each category
SELECT
    p.category,
    AVG(product_revenue) AS avg_revenue_per_product
FROM
(
    SELECT
        product_key,
        SUM(sales_amount) AS product_revenue
    FROM gold.fact_sales
    GROUP BY product_key
) t
JOIN gold.dim_products p
    ON p.product_key = t.product_key
GROUP BY p.category
ORDER BY avg_revenue_per_product DESC;
