/*
    Quantify the size of business activity across different dimensions such as customers, products, geography, and categories. scale, size, significance.
*/

-- 1. Total customers by country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;
GO

-- 2. Total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
GO

-- 3. Total customers by marital status
SELECT
    marital_status,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY marital_status
ORDER BY total_customers DESC;
GO

-- 4. Total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;
GO

-- 5. Total products by subcategory
SELECT
    subcategory,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY subcategory
ORDER BY total_products DESC;
GO

-- 6. Average product cost by category
SELECT
    category,
    AVG(cost) AS avg_product_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_product_cost DESC;
GO

-- 7. Total revenue generated by each product category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
GO

-- 8. Total revenue generated by each subcategory
SELECT
    p.subcategory,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC;
GO

-- 9. Total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;
GO

-- 10. Total quantity of items sold by country
SELECT
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;
GO

-- 11. Total quantity of items sold by product category
SELECT
    p.category,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_items_sold DESC;
GO

-- 12. Average revenue per customer by country
SELECT
    c.country,
    AVG(f.sales_amount) AS avg_revenue_per_order
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY avg_revenue_per_order DESC;
GO
